language: ruby
cache: bundler
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install bundler --pre
before_script:
  - bundle exec rake appraisal:install
services:
  - mongodb
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
notifications:
  email: false
branches:
  only:
    - master
    - development
