language: ruby

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install bundler --pre

before_script:
  - bundle exec rake appraisal:install

services:
  - mongodb

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - jruby-19mode
  - ruby-head
  - jruby-head

sudo: false

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head
